language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir ./build && cd ./build
  - cmake ..
  - make
matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
before_install:
    - eval "${MATRIX_EVAL}"
