language: cpp

script:
  - mkdir ./build && cd ./build
  - cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" ..
  - make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-4.0
    packages:
    - g++-4.9
    - clang-4.0
    - libseccomp-dev

matrix:
  include:
    # works on Trusty
    - os: linux
      env: MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9" BUILD_TYPE=Release
    - os: linux
      env: MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9" BUILD_TYPE=Debug
    - os: linux
      env: MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0" BUILD_TYPE=Release
    - os: linux
      env: MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0" BUILD_TYPE=Debug

before_install:
    - eval "${MATRIX_EVAL}"
